_wandb:
    value:
        cli_version: 0.25.1
        e:
            9xmbaqhxgc48k44ad0c03bj80vovp2ce:
                args:
                    - --config
                    - configs/tomatompra.json
                codePath: scripts/1_finetune/train_deeptomato.py
                codePathLocal: scripts/1_finetune/train_deeptomato.py
                cpu_count: 10
                cpu_count_logical: 20
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1967317549056"
                        used: "827104546816"
                email: kachu@cshl.edu
                executable: /home/kachu/alphagenome-encoder-ft/.venv/bin/python3
                git:
                    commit: 760f16ac7a6d9b7be8f30a200c026a5de3152794
                    remote: git@github.com:katelynsyc/alphagenome-encoder-ft.git
                gpu: NVIDIA RTX A6000
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-689ce07c-ec6e-9057-f1b4-21003811cee8
                    - architecture: Turing
                      cudaCores: 4608
                      memoryTotal: "25769803776"
                      name: NVIDIA TITAN RTX
                      uuid: GPU-6180fd04-afaa-1441-da56-c7936a6dd116
                host: simcoe
                memory:
                    total: "134723792896"
                os: Linux-6.8.0-134-generic-x86_64-with-glibc2.39
                program: /home/kachu/alphagenome-encoder-ft/scripts/1_finetune/train_deeptomato.py
                python: CPython 3.14.5
                root: /home/kachu/alphagenome-encoder-ft
                startedAt: "2026-07-02T15:16:10.457239Z"
                writerId: 9xmbaqhxgc48k44ad0c03bj80vovp2ce
        m: []
        python_version: 3.14.5
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.14.5
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
checkpoint:
    value:
        checkpoint_dir: ./results/deeptomato
        pretrained_weights: null
        save_mode: minimal
data:
    value:
        barcode_min: 10
        barcode_min_eval: 10
        barcode_seq: null
        batch_size: 16
        input_tsv: null
        left_adapter_seq: null
        max_shift: 20
        num_workers: 0
        pin_memory: false
        promoter_seq: null
        random_shift: false
        rc_prob: 0.5
        reverse_complement: false
        right_adapter_seq: null
        sequence_length: 160
        shift_prob: 0.5
        split_mode: deng
        subset_frac: 1
        test_chroms:
            - ch06
        test_txt: metadata/test.txt
        train_frac: 0.8
        train_txt: metadata/train.txt
        val_chroms:
            - ch03
        val_frac: 0.1
        weight_scheme: none
head:
    value:
        activation: relu
        center_bp: null
        dropout: 0.5
        head_type: deeptomato
        hidden_sizes:
            - 256
            - 256
        num_outputs: 2
        pooling_type: flatten
logging:
    value:
        use_wandb: true
        wandb_name: deeptomato
        wandb_project: plantmpra
optim:
    value:
        gradient_accumulation_steps: 1
        gradient_clip: null
        learning_rate: 0.001
        lr_scheduler: constant
        optimizer: adam
        plateau_factor: 0.5
        plateau_min_lr: 0
        plateau_mode: min
        plateau_patience: 2
        weight_decay: 0
runtime:
    value:
        device: null
        seed: 42
        use_amp: false
stage:
    value:
        early_stopping_patience: 10
        num_epochs: 200
        resume_from_stage2: false
        second_stage_epochs: 10
        second_stage_lr: null
        val_evals_per_epoch: 1
